import type { SqlDialect, SqlDriver } from "./types";

function normalizeParam(value: unknown): string | number | bigint | null | Uint8Array {
  if (value === undefined || value === null) return null;
  if (typeof value === "boolean") return value ? 1 : 0;
  if (value instanceof Date) return value.toISOString();
  if (typeof value === "bigint" || typeof value === "number" || typeof value === "string") {
    return value;
  }
  if (value instanceof Uint8Array) return value;
  return JSON.stringify(value);
}

export function toPgPlaceholders(sql: string): string {
  let index = 0;
  return sql.replace(/\?/g, () => `$${(index += 1)}`);
}

export function applyDialectTokens(sql: string, dialect: SqlDialect): string {
  const autoId =
    dialect === "postgres"
      ? "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
      : "INTEGER PRIMARY KEY AUTOINCREMENT";
  return sql.replace(/\{\{AUTO_ID\}\}/g, autoId);
}

interface SqliteStatement {
  all(...params: unknown[]): Record<string, unknown>[];
  run(...params: unknown[]): { changes: number | bigint; lastInsertRowid: number | bigint };
}

interface SqliteDatabase {
  prepare(sql: string): SqliteStatement;
  exec(sql: string): void;
  close(): void;
}

export class SqliteDriver implements SqlDriver {
  readonly dialect: SqlDialect = "sqlite";
  private queue: Promise<unknown> = Promise.resolve();

  constructor(private readonly db: SqliteDatabase) {}

  static async open(path: string, migrations: string[]): Promise<SqliteDriver> {
    const { DatabaseSync } = await import("node:sqlite");
    const db = new DatabaseSync(path) as unknown as SqliteDatabase;
    db.exec("PRAGMA journal_mode = WAL;");
    db.exec("PRAGMA foreign_keys = ON;");
    db.exec("PRAGMA busy_timeout = 5000;");
    const driver = new SqliteDriver(db);
    for (const migration of migrations) {
      db.exec(applyDialectTokens(migration, "sqlite"));
    }
    return driver;
  }

  async query<T>(sql: string, params: unknown[] = []): Promise<T[]> {
    const statement = this.db.prepare(sql);
    const rows = statement.all(...params.map(normalizeParam));
    return rows as T[];
  }

  async one<T>(sql: string, params: unknown[] = []): Promise<T | null> {
    const rows = await this.query<T>(sql, params);
    return rows.length > 0 ? rows[0] : null;
  }

  async execute(sql: string, params: unknown[] = []): Promise<void> {
    const statement = this.db.prepare(sql);
    statement.run(...params.map(normalizeParam));
  }

  async run(sql: string, params: unknown[] = []): Promise<number> {
    const statement = this.db.prepare(sql);
    const result = statement.run(...params.map(normalizeParam));
    return Number(result.changes);
  }

  /** SQLite has a single writer; serialise transactions so they cannot interleave. */
  async transaction<T>(fn: (tx: SqlDriver) => Promise<T>): Promise<T> {
    const run = async (): Promise<T> => {
      this.db.exec("BEGIN IMMEDIATE;");
      try {
        const result = await fn(this);
        this.db.exec("COMMIT;");
        return result;
      } catch (error) {
        try {
          this.db.exec("ROLLBACK;");
        } catch {
          // ignore rollback failures on an already-closed transaction
        }
        throw error;
      }
    };
    const chained = this.queue.then(run, run);
    this.queue = chained.catch(() => undefined);
    return chained;
  }

  async close(): Promise<void> {
    this.db.close();
  }
}

export class PostgresDriver implements SqlDriver {
  readonly dialect: SqlDialect = "postgres";

  constructor(
    private readonly pool: { query: (sql: string, params?: unknown[]) => Promise<{ rows: unknown[]; rowCount?: number | null }>; end: () => Promise<void> },
    private readonly acquire?: () => Promise<{
      query: (sql: string, params?: unknown[]) => Promise<{ rows: unknown[]; rowCount?: number | null }>;
      release: () => void;
    }>,
  ) {}

  static async open(connectionString: string, migrations: string[]): Promise<PostgresDriver> {
    const { Pool } = await import("pg");
    const pool = new Pool({
      connectionString,
      max: 8,
      idleTimeoutMillis: 20_000,
      ssl: connectionString.includes("sslmode=require") ? { rejectUnauthorized: false } : undefined,
    });
    const driver = new PostgresDriver(
      pool as unknown as ConstructorParameters<typeof PostgresDriver>[0],
      async () => {
        const client = await pool.connect();
        return {
          query: (sql, params) => client.query(sql, params),
          release: () => client.release(),
        };
      },
    );
    for (const migration of migrations) {
      await pool.query(applyDialectTokens(migration, "postgres"));
    }
    return driver;
  }

  async query<T>(sql: string, params: unknown[] = []): Promise<T[]> {
    const result = await this.pool.query(toPgPlaceholders(sql), params.map(normalizeParam));
    return result.rows as T[];
  }

  async one<T>(sql: string, params: unknown[] = []): Promise<T | null> {
    const rows = await this.query<T>(sql, params);
    return rows.length > 0 ? rows[0] : null;
  }

  async execute(sql: string, params: unknown[] = []): Promise<void> {
    await this.pool.query(toPgPlaceholders(sql), params.map(normalizeParam));
  }

  async run(sql: string, params: unknown[] = []): Promise<number> {
    const result = await this.pool.query(toPgPlaceholders(sql), params.map(normalizeParam));
    return Number(result.rowCount ?? 0);
  }

  async transaction<T>(fn: (tx: SqlDriver) => Promise<T>): Promise<T> {
    if (!this.acquire) {
      throw new Error("Postgres driver was created without a client factory");
    }
    const client = await this.acquire();
    const scoped: SqlDriver = {
      dialect: "postgres",
      query: async <R>(sql: string, params: unknown[] = []) => {
        const result = await client.query(toPgPlaceholders(sql), params.map(normalizeParam));
        return result.rows as R[];
      },
      one: async <R>(sql: string, params: unknown[] = []) => {
        const result = await client.query(toPgPlaceholders(sql), params.map(normalizeParam));
        return (result.rows[0] as R) ?? null;
      },
      execute: async (sql: string, params: unknown[] = []) => {
        await client.query(toPgPlaceholders(sql), params.map(normalizeParam));
      },
      run: async (sql: string, params: unknown[] = []) => {
        const result = await client.query(toPgPlaceholders(sql), params.map(normalizeParam));
        return Number(result.rowCount ?? 0);
      },
      transaction: async <R>(inner: (tx: SqlDriver) => Promise<R>) => inner(scoped),
      close: async () => undefined,
    };
    try {
      await client.query("BEGIN");
      const result = await fn(scoped);
      await client.query("COMMIT");
      return result;
    } catch (error) {
      try {
        await client.query("ROLLBACK");
      } catch {
        // ignore
      }
      throw error;
    } finally {
      client.release();
    }
  }

  async close(): Promise<void> {
    await this.pool.end();
  }
}
